name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you! Submit an issue can help everybody!'' first issue'
        pr-message: 'Thank you for contributing us! We will read your Pull Request!'' first pr'
